services:
  - type: keyvalue
    name: sentinel-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: sentinel-rate
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: sentinel-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: sentinel-redis
          property: port
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
