
databases:
  - name: sentinel-postgres
    plan: free
    databaseName: sentineldb
    user: sentinel

services:
  - type: keyvalue
    name: sentinel-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: sentinel-rate
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: sentinel-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: sentinel-redis
          property: port
      - key: DB_HOST
        fromDatabase:
          name: sentinel-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sentinel-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: sentinel-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: sentinel-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sentinel-postgres
          property: password
